Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@fixxyzeal 
fixxyzeal
/
API_GateWay
2
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
API_GateWay/.github/workflows/main.yml
@fixxyzeal
fixxyzeal fix missing tag name
Latest commit d350891 on Mar 21, 2020
 History
 1 contributor
36 lines (32 sloc)  1.16 KB
  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
      - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    -   # build image
      run: |
          pushd ./FS_API_GateWays/FS_API_GateWays/
          docker info
          docker build -t fsapigateways -f Dockerfile .
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'fsapigateways' }}
    
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker tag fsapigateways registry.heroku.com/$APP_NAME/web
        docker push registry.heroku.com/$APP_NAME/web                
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:release web -a $APP_NAME
